import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {T} from "@tolgee/react";
import LocaleSwitcher from "../component/LanguageSwitcher";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <LocaleSwitcher/>

            <main className={styles.main}>
                <h1><T>hello_world</T></h1>
                <p><T>translated_with_tolgee</T></p>
            </main>
        </div>
    )
}

export default Home
